import type {
  CatalogCollection,
  CatalogProduct,
} from "./generate";

/** Catalog and collections for a scenario slug. */
export interface ScenarioCatalog {
  catalog: CatalogProduct[];
  collections: CatalogCollection[];
}

const BLOOM_CATALOG: CatalogProduct[] = [
  {
    store_id: "bloom-vitamin-c-serum",
    title: "Vitamin C Brightening Serum",
    product_type: "Serum",
    price_mean: 899,
    price_std: 60,
    revenue_share: 0.24,
    variants: ["30ml", "50ml"],
  },
  {
    store_id: "bloom-collagen-peptides",
    title: "Marine Collagen Peptides",
    product_type: "Supplement",
    price_mean: 1299,
    price_std: 90,
    revenue_share: 0.2,
    variants: ["250g", "500g"],
  },
  {
    store_id: "bloom-ashwagandha",
    title: "Ashwagandha Stress Relief",
    product_type: "Supplement",
    price_mean: 749,
    price_std: 50,
    revenue_share: 0.16,
    variants: ["60 caps", "120 caps"],
  },
  {
    store_id: "bloom-wellness-kit",
    title: "Daily Wellness Starter Kit",
    product_type: "Kit",
    price_mean: 1599,
    price_std: 120,
    revenue_share: 0.18,
    variants: ["Standard"],
  },
  {
    store_id: "bloom-sleep-blend",
    title: "Sleep Support Herbal Blend",
    product_type: "Supplement",
    price_mean: 649,
    price_std: 45,
    revenue_share: 0.12,
    variants: ["30 night supply"],
  },
  {
    store_id: "bloom-probiotic",
    title: "Gut Health Probiotic Daily",
    product_type: "Supplement",
    price_mean: 899,
    price_std: 70,
    revenue_share: 0.1,
    variants: ["30 sachets"],
  },
  {
    store_id: "bloom-detox-tea-old",
    title: "Detox Herbal Tea (Discontinued)",
    product_type: "Supplement",
    price_mean: 399,
    price_std: 30,
    revenue_share: 0,
    variants: ["20 bags"],
    is_dead: true,
  },
  {
    store_id: "bloom-legacy-multi",
    title: "Legacy Multivitamin Formula",
    product_type: "Supplement",
    price_mean: 499,
    price_std: 40,
    revenue_share: 0,
    variants: ["90 tabs"],
    is_dead: true,
  },
];

const THREADRUSH_CATALOG: CatalogProduct[] = [
  {
    store_id: "tr-tee-classic-black",
    title: "Classic Fit Tee — Black",
    product_type: "Tee",
    price_mean: 499,
    price_std: 40,
    revenue_share: 0.09,
    variants: ["S", "M", "L", "XL"],
  },
  {
    store_id: "tr-tee-classic-white",
    title: "Classic Fit Tee — White",
    product_type: "Tee",
    price_mean: 499,
    price_std: 40,
    revenue_share: 0.08,
    variants: ["S", "M", "L", "XL"],
  },
  {
    store_id: "tr-tee-oversized",
    title: "Oversized Graphic Tee",
    product_type: "Tee",
    price_mean: 599,
    price_std: 50,
    revenue_share: 0.1,
    variants: ["S", "M", "L", "XL"],
  },
  {
    store_id: "tr-hoodie-fleece",
    title: "Fleece Pullover Hoodie",
    product_type: "Hoodie",
    price_mean: 1299,
    price_std: 90,
    revenue_share: 0.12,
    variants: ["S", "M", "L", "XL"],
  },
  {
    store_id: "tr-hoodie-zip",
    title: "Zip-Up Street Hoodie",
    product_type: "Hoodie",
    price_mean: 1499,
    price_std: 100,
    revenue_share: 0.1,
    variants: ["S", "M", "L", "XL"],
  },
  {
    store_id: "tr-jogger-slim",
    title: "Slim Taper Joggers",
    product_type: "Joggers",
    price_mean: 899,
    price_std: 70,
    revenue_share: 0.09,
    variants: ["S", "M", "L", "XL"],
  },
  {
    store_id: "tr-jogger-relaxed",
    title: "Relaxed Fit Joggers",
    product_type: "Joggers",
    price_mean: 949,
    price_std: 75,
    revenue_share: 0.08,
    variants: ["S", "M", "L", "XL"],
  },
  {
    store_id: "tr-tee-sale-navy",
    title: "End-of-Season Tee — Navy",
    product_type: "Tee",
    price_mean: 349,
    price_std: 30,
    revenue_share: 0.07,
    variants: ["M", "L", "XL"],
  },
  {
    store_id: "tr-hoodie-limited",
    title: "Limited Drop Hoodie",
    product_type: "Hoodie",
    price_mean: 1699,
    price_std: 120,
    revenue_share: 0.08,
    variants: ["M", "L", "XL"],
  },
  {
    store_id: "tr-jogger-cargo",
    title: "Cargo Pocket Joggers",
    product_type: "Joggers",
    price_mean: 1099,
    price_std: 85,
    revenue_share: 0.07,
    variants: ["S", "M", "L", "XL"],
  },
  {
    store_id: "tr-tee-tie-dye",
    title: "Tie-Dye Festival Tee",
    product_type: "Tee",
    price_mean: 649,
    price_std: 55,
    revenue_share: 0.06,
    variants: ["S", "M", "L"],
  },
  {
    store_id: "tr-hoodie-crop",
    title: "Cropped Hoodie",
    product_type: "Hoodie",
    price_mean: 999,
    price_std: 80,
    revenue_share: 0.05,
    variants: ["S", "M", "L"],
  },
  {
    store_id: "tr-jogger-track",
    title: "Track Stripe Joggers",
    product_type: "Joggers",
    price_mean: 1049,
    price_std: 80,
    revenue_share: 0.05,
    variants: ["S", "M", "L", "XL"],
  },
  {
    store_id: "tr-tee-bundle",
    title: "3-Pack Basic Tees",
    product_type: "Tee",
    price_mean: 1199,
    price_std: 90,
    revenue_share: 0.06,
    variants: ["Combo S-M-L"],
  },
  {
    store_id: "tr-tee-archived-plaid",
    title: "Archived Plaid Tee",
    product_type: "Tee",
    price_mean: 449,
    price_std: 35,
    revenue_share: 0,
    variants: ["L", "XL"],
    is_dead: true,
  },
  {
    store_id: "tr-hoodie-old-logo",
    title: "Old Logo Hoodie",
    product_type: "Hoodie",
    price_mean: 799,
    price_std: 60,
    revenue_share: 0,
    variants: ["M", "L"],
    is_dead: true,
  },
  {
    store_id: "tr-jogger-discontinued",
    title: "Discontinued Slim Jogger",
    product_type: "Joggers",
    price_mean: 699,
    price_std: 50,
    revenue_share: 0,
    variants: ["M", "L"],
    is_dead: true,
  },
  {
    store_id: "tr-tee-clearance-grey",
    title: "Clearance Grey Tee",
    product_type: "Tee",
    price_mean: 299,
    price_std: 25,
    revenue_share: 0,
    variants: ["S", "M"],
    is_dead: true,
  },
];

const FANVAULT_CATALOG: CatalogProduct[] = [
  {
    store_id: "fv-cricket-jersey",
    title: "National Cricket Replica Jersey",
    product_type: "Jersey",
    price_mean: 1499,
    price_std: 120,
    revenue_share: 0.18,
    variants: ["S", "M", "L", "XL"],
  },
  {
    store_id: "fv-cricket-cap",
    title: "Team Logo Cap",
    product_type: "Accessory",
    price_mean: 599,
    price_std: 50,
    revenue_share: 0.1,
    variants: ["One Size"],
  },
  {
    store_id: "fv-anime-figure",
    title: "Limited Anime Figure",
    product_type: "Collectible",
    price_mean: 2499,
    price_std: 200,
    revenue_share: 0.15,
    variants: ["Standard"],
  },
  {
    store_id: "fv-anime-poster",
    title: "Franchise Poster Set",
    product_type: "Collectible",
    price_mean: 399,
    price_std: 35,
    revenue_share: 0.08,
    variants: ["3-pack"],
  },
  {
    store_id: "fv-superhero-tee",
    title: "Superhero Logo Tee",
    product_type: "Apparel",
    price_mean: 799,
    price_std: 60,
    revenue_share: 0.12,
    variants: ["S", "M", "L", "XL"],
  },
  {
    store_id: "fv-superhero-mug",
    title: "Character Mug",
    product_type: "Accessory",
    price_mean: 449,
    price_std: 40,
    revenue_share: 0.06,
    variants: ["350ml"],
  },
  {
    store_id: "fv-football-scarf",
    title: "Club Scarf",
    product_type: "Accessory",
    price_mean: 899,
    price_std: 70,
    revenue_share: 0.09,
    variants: ["One Size"],
  },
  {
    store_id: "fv-expired-jersey-2023",
    title: "2023 Season Jersey (Expired License)",
    product_type: "Jersey",
    price_mean: 999,
    price_std: 80,
    revenue_share: 0,
    variants: ["L", "XL"],
    is_dead: true,
  },
  {
    store_id: "fv-retired-figure",
    title: "Retired Wave Figure",
    product_type: "Collectible",
    price_mean: 1899,
    price_std: 150,
    revenue_share: 0,
    variants: ["Standard"],
    is_dead: true,
  },
  {
    store_id: "fv-unlicensed-poster",
    title: "Unlicensed Poster (Pulled)",
    product_type: "Collectible",
    price_mean: 199,
    price_std: 20,
    revenue_share: 0,
    variants: ["Single"],
    is_dead: true,
  },
  {
    store_id: "fv-old-tee-design",
    title: "Old Logo Tee Design",
    product_type: "Apparel",
    price_mean: 499,
    price_std: 40,
    revenue_share: 0,
    variants: ["M", "L"],
    is_dead: true,
  },
  {
    store_id: "fv-discontinued-mug",
    title: "Discontinued Character Mug",
    product_type: "Accessory",
    price_mean: 349,
    price_std: 30,
    revenue_share: 0,
    variants: ["350ml"],
    is_dead: true,
  },
  {
    store_id: "fv-clearance-scarf",
    title: "Clearance Scarf",
    product_type: "Accessory",
    price_mean: 399,
    price_std: 35,
    revenue_share: 0,
    variants: ["One Size"],
    is_dead: true,
  },
  {
    store_id: "fv-legacy-cap",
    title: "Legacy Team Cap",
    product_type: "Accessory",
    price_mean: 449,
    price_std: 35,
    revenue_share: 0,
    variants: ["One Size"],
    is_dead: true,
  },
  {
    store_id: "fv-sunset-hoodie",
    title: "Sunset Franchise Hoodie",
    product_type: "Apparel",
    price_mean: 1299,
    price_std: 100,
    revenue_share: 0,
    variants: ["M", "L", "XL"],
    is_dead: true,
  },
];

const GLOWLAB_CATALOG: CatalogProduct[] = [
  {
    store_id: "gl-hero-retinol-serum",
    title: "Advanced Retinol Night Serum",
    product_type: "Serum",
    price_mean: 1499,
    price_std: 120,
    revenue_share: 0.68,
    variants: ["30ml", "50ml"],
  },
  {
    store_id: "gl-cleanser-gel",
    title: "Gentle Gel Cleanser",
    product_type: "Cleanser",
    price_mean: 499,
    price_std: 40,
    revenue_share: 0.12,
    variants: ["100ml", "200ml"],
  },
  {
    store_id: "gl-spf-moisturizer",
    title: "SPF 50 Daily Moisturizer",
    product_type: "Moisturizer",
    price_mean: 699,
    price_std: 55,
    revenue_share: 0.1,
    variants: ["50ml"],
  },
  {
    store_id: "gl-toner-phaseout",
    title: "Balancing Toner (Phase Out)",
    product_type: "Toner",
    price_mean: 399,
    price_std: 30,
    revenue_share: 0,
    variants: ["150ml"],
    is_dead: true,
  },
  {
    store_id: "gl-mask-discontinued",
    title: "Clay Mask (Discontinued)",
    product_type: "Mask",
    price_mean: 549,
    price_std: 45,
    revenue_share: 0,
    variants: ["75ml"],
    is_dead: true,
  },
  {
    store_id: "gl-eye-cream-old",
    title: "Old Formula Eye Cream",
    product_type: "Eye Care",
    price_mean: 799,
    price_std: 60,
    revenue_share: 0,
    variants: ["15ml"],
    is_dead: true,
  },
  {
    store_id: "gl-lip-balm-legacy",
    title: "Legacy Lip Balm",
    product_type: "Lip Care",
    price_mean: 249,
    price_std: 20,
    revenue_share: 0,
    variants: ["4g"],
    is_dead: true,
  },
  {
    store_id: "gl-sample-kit-old",
    title: "Old Sample Discovery Kit",
    product_type: "Kit",
    price_mean: 299,
    price_std: 25,
    revenue_share: 0,
    variants: ["Mini set"],
    is_dead: true,
  },
  {
    store_id: "gl-exfoliant-slow",
    title: "Slow-Moving Exfoliant",
    product_type: "Treatment",
    price_mean: 649,
    price_std: 50,
    revenue_share: 0,
    variants: ["60ml"],
    is_dead: true,
  },
  {
    store_id: "gl-body-lotion-dead",
    title: "Body Lotion (Near Dead)",
    product_type: "Body Care",
    price_mean: 599,
    price_std: 45,
    revenue_share: 0,
    variants: ["200ml"],
    is_dead: true,
  },
];

const EDGECRAFT_CATALOG: CatalogProduct[] = [
  {
    store_id: "ec-trimmer-pro",
    title: "Pro Beard Trimmer",
    product_type: "Grooming Tool",
    price_mean: 2499,
    price_std: 180,
    revenue_share: 0.22,
    variants: ["Standard"],
  },
  {
    store_id: "ec-shaving-kit",
    title: "Precision Shaving Kit",
    product_type: "Kit",
    price_mean: 1299,
    price_std: 100,
    revenue_share: 0.18,
    variants: ["Full kit"],
  },
  {
    store_id: "ec-beard-oil",
    title: "Beard Growth Oil",
    product_type: "Consumable",
    price_mean: 649,
    price_std: 50,
    revenue_share: 0.14,
    variants: ["30ml", "60ml"],
  },
  {
    store_id: "ec-aftershave",
    title: "Cooling Aftershave Balm",
    product_type: "Consumable",
    price_mean: 499,
    price_std: 40,
    revenue_share: 0.12,
    variants: ["100ml"],
  },
  {
    store_id: "ec-razor-blades",
    title: "Safety Razor Blade Pack",
    product_type: "Consumable",
    price_mean: 399,
    price_std: 30,
    revenue_share: 0.1,
    variants: ["10 pack"],
  },
  {
    store_id: "ec-face-wash",
    title: "Charcoal Face Wash",
    product_type: "Consumable",
    price_mean: 449,
    price_std: 35,
    revenue_share: 0.1,
    variants: ["150ml"],
  },
  {
    store_id: "ec-styling-wax",
    title: "Matte Styling Wax",
    product_type: "Consumable",
    price_mean: 549,
    price_std: 45,
    revenue_share: 0.08,
    variants: ["75g"],
  },
  {
    store_id: "ec-comb-set",
    title: "Wooden Comb Set",
    product_type: "Accessory",
    price_mean: 299,
    price_std: 25,
    revenue_share: 0.06,
    variants: ["3-piece"],
  },
  {
    store_id: "ec-gift-box",
    title: "Grooming Gift Box",
    product_type: "Kit",
    price_mean: 1999,
    price_std: 150,
    revenue_share: 0.1,
    variants: ["Deluxe"],
  },
  {
    store_id: "ec-old-trimmer",
    title: "Gen-1 Trimmer (Discontinued)",
    product_type: "Grooming Tool",
    price_mean: 1499,
    price_std: 120,
    revenue_share: 0,
    variants: ["Standard"],
    is_dead: true,
  },
  {
    store_id: "ec-legacy-cream",
    title: "Legacy Shaving Cream",
    product_type: "Consumable",
    price_mean: 349,
    price_std: 30,
    revenue_share: 0,
    variants: ["200ml"],
    is_dead: true,
  },
  {
    store_id: "ec-clearance-soap",
    title: "Clearance Bar Soap",
    product_type: "Consumable",
    price_mean: 199,
    price_std: 20,
    revenue_share: 0,
    variants: ["Single"],
    is_dead: true,
  },
];

const SLUMBERCO_CATALOG: CatalogProduct[] = [
  {
    store_id: "sc-mattress-queen",
    title: "CloudRest Queen Mattress",
    product_type: "Mattress",
    price_mean: 54999,
    price_std: 3000,
    revenue_share: 0.45,
    variants: ["Queen", "King"],
  },
  {
    store_id: "sc-pillow-memory",
    title: "Memory Foam Pillow",
    product_type: "Pillow",
    price_mean: 3999,
    price_std: 400,
    revenue_share: 0.2,
    variants: ["Standard", "Contour"],
  },
  {
    store_id: "sc-duvet-premium",
    title: "Premium Weighted Duvet",
    product_type: "Bedding",
    price_mean: 8999,
    price_std: 700,
    revenue_share: 0.18,
    variants: ["Queen", "King"],
  },
  {
    store_id: "sc-sheet-set",
    title: "Cooling Cotton Sheet Set",
    product_type: "Bedding",
    price_mean: 4999,
    price_std: 350,
    revenue_share: 0.1,
    variants: ["Queen", "King"],
  },
  {
    store_id: "sc-mattress-protector",
    title: "Waterproof Mattress Protector",
    product_type: "Accessory",
    price_mean: 2499,
    price_std: 200,
    revenue_share: 0.07,
    variants: ["Queen", "King"],
  },
  {
    store_id: "sc-travel-pillow-old",
    title: "Travel Pillow (Discontinued)",
    product_type: "Pillow",
    price_mean: 1499,
    price_std: 120,
    revenue_share: 0,
    variants: ["Compact"],
    is_dead: true,
  },
];

const BLOOM_COLLECTIONS: CatalogCollection[] = [
  {
    title: "Daily Wellness",
    collection_type: "custom",
    product_store_ids: [
      "bloom-vitamin-c-serum",
      "bloom-collagen-peptides",
      "bloom-ashwagandha",
      "bloom-probiotic",
    ],
  },
  {
    title: "Starter Kits",
    collection_type: "custom",
    product_store_ids: ["bloom-wellness-kit", "bloom-sleep-blend"],
  },
];

const THREADRUSH_COLLECTIONS: CatalogCollection[] = [
  {
    title: "Tees",
    collection_type: "custom",
    product_store_ids: [
      "tr-tee-classic-black",
      "tr-tee-classic-white",
      "tr-tee-oversized",
      "tr-tee-sale-navy",
      "tr-tee-tie-dye",
      "tr-tee-bundle",
    ],
  },
  {
    title: "Hoodies & Joggers",
    collection_type: "custom",
    product_store_ids: [
      "tr-hoodie-fleece",
      "tr-hoodie-zip",
      "tr-jogger-slim",
      "tr-jogger-relaxed",
      "tr-jogger-cargo",
    ],
  },
];

const FANVAULT_COLLECTIONS: CatalogCollection[] = [
  {
    title: "Cricket",
    collection_type: "custom",
    product_store_ids: ["fv-cricket-jersey", "fv-cricket-cap", "fv-football-scarf"],
  },
  {
    title: "Anime & Superhero",
    collection_type: "custom",
    product_store_ids: [
      "fv-anime-figure",
      "fv-anime-poster",
      "fv-superhero-tee",
      "fv-superhero-mug",
    ],
  },
];

const GLOWLAB_COLLECTIONS: CatalogCollection[] = [
  {
    title: "Hero Serum",
    collection_type: "custom",
    product_store_ids: ["gl-hero-retinol-serum"],
  },
  {
    title: "Daily Essentials",
    collection_type: "custom",
    product_store_ids: ["gl-cleanser-gel", "gl-spf-moisturizer"],
  },
];

const EDGECRAFT_COLLECTIONS: CatalogCollection[] = [
  {
    title: "Tools",
    collection_type: "custom",
    product_store_ids: ["ec-trimmer-pro", "ec-shaving-kit", "ec-comb-set"],
  },
  {
    title: "Consumables",
    collection_type: "custom",
    product_store_ids: [
      "ec-beard-oil",
      "ec-aftershave",
      "ec-razor-blades",
      "ec-face-wash",
      "ec-styling-wax",
    ],
  },
];

const SLUMBERCO_COLLECTIONS: CatalogCollection[] = [
  {
    title: "Mattresses",
    collection_type: "custom",
    product_store_ids: ["sc-mattress-queen"],
  },
  {
    title: "Sleep Accessories",
    collection_type: "custom",
    product_store_ids: [
      "sc-pillow-memory",
      "sc-duvet-premium",
      "sc-sheet-set",
      "sc-mattress-protector",
    ],
  },
];

const CATALOGS: Record<string, ScenarioCatalog> = {
  bloom: { catalog: BLOOM_CATALOG, collections: BLOOM_COLLECTIONS },
  threadrush: {
    catalog: THREADRUSH_CATALOG,
    collections: THREADRUSH_COLLECTIONS,
  },
  fanvault: { catalog: FANVAULT_CATALOG, collections: FANVAULT_COLLECTIONS },
  glowlab: { catalog: GLOWLAB_CATALOG, collections: GLOWLAB_COLLECTIONS },
  edgecraft: {
    catalog: EDGECRAFT_CATALOG,
    collections: EDGECRAFT_COLLECTIONS,
  },
  slumberco: {
    catalog: SLUMBERCO_CATALOG,
    collections: SLUMBERCO_COLLECTIONS,
  },
};

/**
 * Returns the hardcoded product catalog and collections for a scenario slug.
 *
 * @param scenarioId - Profile key, e.g. `"bloom"`.
 */
export function getScenarioCatalog(scenarioId: string): ScenarioCatalog {
  return (
    CATALOGS[scenarioId] ?? {
      catalog: [],
      collections: [],
    }
  );
}
